version: '3.8'

services:
  backend:
    build: ./backend
    container_name: blockchain_backend
    ports:
      - "4000:4000"
    depends_on:
      - db
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: blockchain_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: mongo
    container_name: blockchain_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
